MonSite/src/Entity/Application.php
<?php

namespace App\Entity;

use App\Repository\ApplicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ApplicationRepository::class)
 */
class Application
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $date_debut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\ManyToMany(targetEntity=Skill::class, mappedBy="application")
     */
    private $skills;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="application")
     */
    private $pictures;

    /**
     * @ORM\ManyToMany(targetEntity=Software::class, mappedBy="application")
     */
    private $software;

    /**
     * @ORM\OneToMany(targetEntity=Doc::class, mappedBy="application")
     */
    private $docs;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $repo_url;

    /**
     * @ORM\Column(type="string", length=600, nullable=true)
     */
    private $intro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title2;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $text1;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $text2;

    

    public function __construct()
    {
        $this->audiovisuel = new ArrayCollection();
        $this->skills = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->software = new ArrayCollection();
        $this->docs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDateDebut(): ?string
    {
        return $this->date_debut;
    }

    public function setDateDebut(?string $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?string
    {
        return $this->date_fin;
    }

    public function setDateFin(?string $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection|Skill[]
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
            $skill->addApplication($this);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        if ($this->skills->removeElement($skill)) {
            $skill->removeApplication($this);
        }

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setApplication($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getApplication() === $this) {
                $picture->setApplication(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Software[]
     */
    public function getSoftware(): Collection
    {
        return $this->software;
    }

    public function addSoftware(Software $software): self
    {
        if (!$this->software->contains($software)) {
            $this->software[] = $software;
            $software->addApplication($this);
        }

        return $this;
    }

    public function removeSoftware(Software $software): self
    {
        if ($this->software->removeElement($software)) {
            $software->removeApplication($this);
        }

        return $this;
    }

    /**
     * @return Collection|Doc[]
     */
    public function getDocs(): Collection
    {
        return $this->docs;
    }

    public function addDoc(Doc $doc): self
    {
        if (!$this->docs->contains($doc)) {
            $this->docs[] = $doc;
            $doc->setApplication($this);
        }

        return $this;
    }

    public function removeDoc(Doc $doc): self
    {
        if ($this->docs->removeElement($doc)) {
            // set the owning side to null (unless already changed)
            if ($doc->getApplication() === $this) {
                $doc->setApplication(null);
            }
        }

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getRepoUrl(): ?string
    {
        return $this->repo_url;
    }

    public function setRepoUrl(?string $repo_url): self
    {
        $this->repo_url = $repo_url;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(?string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getTitle1(): ?string
    {
        return $this->title1;
    }

    public function setTitle1(?string $title1): self
    {
        $this->title1 = $title1;

        return $this;
    }

    public function getTitle2(): ?string
    {
        return $this->title2;
    }

    public function setTitle2(?string $title2): self
    {
        $this->title2 = $title2;

        return $this;
    }

    public function getText1(): ?string
    {
        return $this->text1;
    }

    public function setText1(?string $text1): self
    {
        $this->text1 = $text1;

        return $this;
    }

    public function getText2(): ?string
    {
        return $this->text2;
    }

    public function setText2(?string $text2): self
    {
        $this->text2 = $text2;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

MonSite/src/Form/ApplicationType.php
<?php

namespace App\Form;

use App\Entity\Application;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApplicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Application::class,
        ]);
    }
}

MonSite/src/Controller/ApplicationController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Form\ApplicationType;
use App\Repository\ApplicationRepository;
use App\Repository\DocRepository;
use App\Repository\PictureRepository;
use App\Repository\SkillRepository;
use App\Repository\SoftwareRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/application")
 */
class ApplicationController extends AbstractController
{
    /**
     * @Route("/", name="application_index", methods={"GET"})
     */
    public function index(ApplicationRepository $applicationRepository): Response
    {
        return $this->render('application/index.html.twig', [
            'applications' => $applicationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="application_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $application = new Application();
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($application);
            $entityManager->flush();

            return $this->redirectToRoute('application_index');
        }

        return $this->render('application/new.html.twig', [
            'application' => $application,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="application_show", methods={"GET"})
     */
    public function show(Application $application, SoftwareRepository $softwareRepository, SkillRepository $skillRepository, DocRepository $docs, PictureRepository $pictures): Response
    {
        return $this->render('application/show.html.twig', [
            'application' => $application,
            'softwares' => $softwareRepository->findSoftwareByApplication($application->getId()),
            'skills' => $skillRepository->findSkillByApplication($application->getId()),
            'docs' => $docs->findDocByApplication($application->getId()), 
            'pictures' => $pictures->findPicturebyApplication($application->getId())
        ]);
    }

    /**
     * @Route("/{id}/edit", name="application_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Application $application): Response
    {
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('application_index');
        }

        return $this->render('application/edit.html.twig', [
            'application' => $application,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="application_delete", methods={"POST"})
     */
    public function delete(Request $request, Application $application): Response
    {
        if ($this->isCsrfTokenValid('delete'.$application->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($application);
            $entityManager->flush();
        }

        return $this->redirectToRoute('application_index');
    }
}

MonSite/templates/application/_delete_form.html.twig
<form method="post" action="{{ path('application_delete', {'id': application.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ application.id) }}">
    <button class="btn">Delete</button>
</form>

MonSite/templates/application/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Application{% endblock %}

{% block body %}
    <h1>Edit Application</h1>

    {{ include('application/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('application_index') }}">back to list</a>

    {{ include('application/_delete_form.html.twig') }}
{% endblock %}

MonSite/templates/application/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application index{% endblock %}

{% block body %}
    <h1>Mes Applications</h1>
        <div class= "production_index">
            {% for application in applications %}
                        <a class="production_index_exemple" href="{{ path('application_show', {'id': application.id}) }}">{{ application.name }}</a>
            {% else %}
                <tr>
                    <td colspan="3">no records found</td>
                </tr>
            {% endfor %}
            {% if "ROLE_ADMIN" in app.user.roles %}
            <a href="{{ path('application_new') }}">Create new</a>
            {% endif %}
        </div>
{% endblock %}




    {# <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for application in applications %}
            <tr>
                <td>{{ application.id }}</td>
                <td>{{ application.name }}</td>
                <td>
                    <a href="{{ path('application_show', {'id': application.id}) }}">show</a>
                    <a href="{{ path('application_edit', {'id': application.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> #}

    

MonSite/templates/application/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Application{% endblock %}

{% block body %}
    <h1>Create new Application</h1>

    {{ include('application/_form.html.twig') }}

    <a href="{{ path('application_index') }}">back to list</a>
{% endblock %}

MonSite/templates/application/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application{% endblock %}

{% block body %}


<div class="show_page">
        <header class="show_header">
            {# <a class="nav_bar_item" href="{{ path('production') }}">Retour à la liste</a> #}
            <div class="show_header_title">
                {# <a class="nav_button" href="#">&#8249;</a> #}
                <div>
                    <h1 class="show_title">{{ application.name }}</h1>
                </div>
                
                {# <a class="nav_button" href="#">&#8250;</a> #}
            </div>
            <h4 class="subtitle">{{ application.subtitle }}</h4>
            <h5 class="subtitle">{{ application.dateDebut }} -> {{ application.dateFin }}</h5>
        </header>
        <div class="show_body">
            <div class="show_left">
                {% if ((application.url is not null) or (application.repoUrl is not null)) %}
                    <div class="show_box">
                        <h3 class="show_box_title">Liens</h3>
                        <ul class="show_list">
                            {% if (application.repoUrl is not null) %}
                            <li class="show_list_item"><a class="show_list_url" href="{{ application.repoUrl }}">Repo Github</a></li>
                            {% endif %}
                            {% if (application.url is not null) %}
                            <li class="show_list_item"><a class="show_list_url" href="{{ application.url }}">lien vers le site</a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
                
                <div class="show_box">
                    <h3 class="show_box_title">Logiciels & Langages utilisés</h3>
                    <ul class="show_list">
                        {% for software in softwares %}
                        <li class="show_list_item">
                            <div>{{ software.name }}</div>
                            {# <div>&#9733;&#9733;&#9733;&#9733;&#9733;</div> #}
                        </li>
                        {% endfor %}
                        
                    </ul>
                    <ul class="show_list">
                        {% for skill in skills %}
                        <li class="show_list_item">
                            <div>{{ skill.name }}</div>
                            {# <div>&#9733;&#9733;&#9733;&#9733;&#9733;</div> #}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                
            </div>
            <div class="show_center">
                <p>{{ application.intro }}</p>
                <h4>{{ application.title1 }}</h4>
                <p>{{ application.text1 }}</p>
                <h4>{{ application.title2 }}</h4>
                <p>{{ application.text2 }}</p>
            </div>
            <div class="show_right">
                <div class="show_box">
                    <h3 class="show_box_title">Documents</h3>
                    {% for doc in docs %}
                    <a class="production_card_link" id="application_doc" href="{{ asset(doc.path) }}">
                        <div class="production_card_exemple">
                            <h4>{{ doc.name }}</h4>
                        </div>
                    </a>
                    {% else %}
                    {% endfor %}
                </div>
                {# {% if pictures.O is defined %} #}
                    <div class="show_box">
                        <h3 class="show_box_title">Images</h3>
                        <div class="box_picture_content">
                        {% for picture in pictures %}
                            <a class="production_card_picture" href="{{ asset(picture.path) }}">
                                    <img class="production_card_picture_element" src="{{ asset(picture.path) }}"
                                        alt="
                                            {% if picture.name is defined %}
                                                {{ picture.name }}
                                            {% endif %}
                                            ">
                            </a>
                        {% else %}
                        {% endfor %}
                            {% if "ROLE_ADMIN" in app.user.roles %}
                            <a class="production_card_picture" href="{{ path('picture_new') }}">
                                <div class="">
                                    <img class="production_card_picture_element" src="{{ asset('assets/images/habillage/plus.png') }}" alt="">
                                </div>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                {# {% endif %} #}
            </div>
        </div>
    </div>
    {% if "ROLE_ADMIN" in app.user.roles %}
        {{ include('application/_delete_form.html.twig') }}
    {% endif %}
    {# <h1>Application</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ application.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ application.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('application_index') }}">back to list</a>

    <a href="{{ path('application_edit', {'id': application.id}) }}">edit</a>

    {{ include('application/_delete_form.html.twig') }} #}
{% endblock %}